contact_links:
  - name: Discord
    about: Hedystia Discord
    url: https://hedystia.com/support
  - name: WhatsApp
    about: Hedystia WhatsApp
    url: https://whatsapp.com/channel/0029VaBmaSI2Jl8FwbQLTH1c
  - name: BoxMineWorld
    about: Free/Paid Hosting
    url: https://boxmineworld.com
  - name: BoxMineWorld Discord
    about: Free/Paid Hosting Discord
    url: https://discord.gg/84qsr4v
