contact_links:
  - name: Discord
    url: https://hedystia.com/support
  - name: WhatsApp
    url: https://whatsapp.com/channel/0029VaBmaSI2Jl8FwbQLTH1c
  - name: BoxMine World
    about: Free/Paid Hosting
    url: https://boxmineworld.com
  - name: BoxMine World Discord
    about: Free/Paid Hosting Discord
    url: https://discord.gg/84qsr4v
